### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by wh00pwh00p** [emqtt/CocoaMQTT#104]
Is there a version to use CocoaMQTT with Swift 2.3? As far as I can tell, the current version only works for Swift 3.0 right?

**Comment by CrazyWisdom** [comment]
1.0.9 works for Swift 2.3.
1.0.10 only works for Swift 3.0.

**Comment by wh00pwh00p** [comment]
Thank you! If I change my pod file to `CocoaMQTT (~> 1.0.9)` and run `pod install`, the version 1.0.10 gets installed. Any idea how I can get the right version?

**Comment by CrazyWisdom** [comment]
target 'Example' do
    pod 'CocoaMQTT', '1.0.9'
end

**Comment by CrazyWisdom** [comment]
```
target 'Example' do
  pod 'CocoaMQTT', '1.0.9'
end
```

**Comment by wh00pwh00p** [comment]
...feeling slightly stupid, I thank you very much! 👍 :)

**Comment by 4seas** [comment]
For Carthage users with Xcode 8 and Swift 2.3

Cartfile
`github "4seas/CocoaMQTT" "1.0.9.23"`

will also send a pull request
