### ISSUE TITLE
Disconnect on bad connection

### ISSUE THREAD

**Issue by brunoudi** [emqtt/CocoaMQTT#105]
I don't know if there is a bug or just a misunderstanding by my part.
When I connect over a bad 3G signal, in a while it stops receiving answers from ping ("pong").
In my opinion it should fire mqttDidDisconnect.
Is my understanding correct, or I have to implement a way to check that?

**Comment by CrazyWisdom** [comment]
@brunoudi 
Is it in the state of  locked screen  or is APP switched to the background? If neither, you may need to handle the reconnection by yourself.

**Comment by NancyZY** [comment]
How to deal with the reconnection, I try to mqttDidDisconnect method call the connection method, Is it right action?

**Comment by CrazyWisdom** [comment]
@NancyZY 
Right.
