### ISSUE TITLE
What is ID stand for in func mqtt didPublishMessage/didReceiveMessage?

### ISSUE THREAD

**Issue by hry625** [emqtt/CocoaMQTT#107]
I am a newbie for iOS and mqtt. I have tried the example, but I don't really understand what is ID stand for in the func didPublishMessage/didReceiveMessage. Also, how should I modify ID if I use other clients(like mqtt-spy) to publish a message to the topic?

**Comment by CrazyWisdom** [comment]
1.`func mqtt(_ mqtt: CocoaMQTT, didReceiveMessage message: CocoaMQTTMessage, id: UInt16 )`
This ID is created by the broker:
In the mode of QOs1,when the broker sends a message to the client, it creates an ID. And if the client receives the message, it needs to carry the ID when sending PUBACK.


2.`func mqtt(_ mqtt: CocoaMQTT, didPublishMessage message: CocoaMQTTMessage, id: UInt16)`
This ID is created by the client:
In the mode of QOs1,when the client sends a message to the broker, it creates an ID. And if the broker receives the message, it needs to carry the ID when sending PUBACK.
