### ISSUE TITLE
GCDAsyncSocket needs updating

### ISSUE THREAD

**Issue by tethridge** [emqtt/CocoaMQTT#110]
See: 
GCDAsyncSocket.startTLS has incorrect type specified in header file
https://github.com/robbiehanson/CocoaAsyncSocket/pull/453/files

This fix needs to be pulled in and CocoaMQTT updated so that values can be properly set in startTLS().  Currently startTLS expects [NSNumber], which prevents the additions of security certificates.

**Comment by CrazyWisdom** [comment]
@tethridge
Thanks.
https://github.com/emqtt/CocoaMQTT/pull/115
