### ISSUE TITLE
import CocoaMQTT dont work

### ISSUE THREAD

**Issue by GusSerra** [emqtt/CocoaMQTT#112]
i'am using xcode 8.1 and Swift 10.1.
i did pod install and i it was installed la version 1.0; Is it correct ?
Well, when i put the import CocoaMQTT at code, the xcode say No Such Module.

What is happening ?

Thanks

**Comment by CrazyWisdom** [comment]
```
➜  ~ pod --version
1.1.0.rc.2
```
The cocoapods version should be  at least  1.1.0.rc.2
