### ISSUE TITLE
global message id resets every time I connect

### ISSUE THREAD

**Issue by avaan** [emqtt/CocoaMQTT#113]
I wanted to retain the global message id (CocoaMQTT.gmid).

Is their any way I can save this value and reset it to old value when I connect back.

**Comment by avaan** [comment]
@CrazyWisdom I am using CocoaMQTT in my project.

I need to generate and control the "gmid" in my application. 

Can you please modify the code to allow to set "gmid" variable of CocoaMQTT?

or can you please provide override functions similar to below

open func publish(msgId:UInt16,  _ message: CocoaMQTTMessage) -> UInt16
open func subscribe(msgId:UInt16, _ topic: String, qos: CocoaMQTTQOS = .qos1)
open func unsubscribe(msgId:UInt16, _ topic: String)

with which I can pass my gmid.

**Comment by avaan** [comment]
@CrazyWisdom @emqplus I am using this framework. Now I am facing some server ack problem with gmid. it will be great if you allow me to handle "gmid" from my application.

**Comment by alexyu1989** [comment]
@avaan Sorry, gmid can not be rewrite. Because gmid is used to distinguish between different messages. If 2 messages have the same id, the server may be confused.

**Comment by avaan** [comment]
@CrazyWisdom thanks for your repose.
