### ISSUE TITLE
Wrong if let binding removes currently subscribed topic from subscriptions

### ISSUE THREAD

**Issue by turushanaktay** [emqtt/CocoaMQTT#119]
that if let binding on line 449. removes that topic from subscriptions, while reporting with didSubscribeTopic, I believe subscriptions should hold that subscribed value as long as user dont unsubscribes to it, this code just removes from subscriptions before any un-sub event occurs.

I think this binding would be better
`if let topic = subscriptions[msgid]`

![screen shot 2016-12-01 at 15 46 03](https://cloud.githubusercontent.com/assets/4019257/20794564/98672a38-b7d5-11e6-924d-f9559c766ff4.png)

**Comment by Spilly** [comment]
This is intentional, they're using the subscriptions array to hold subscriptions that are either in the process of being subscribed to or in the process of being unsubscribed. After being successfully subscribed/unsubcribed they remove them from the array.
