### ISSUE TITLE
Outdated podspec file?

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [emqtt/CocoaMQTT#120]
Hi,

I'm trying to integrate CocoaMQTT to a Swift 3 project via CocoaPods. But the existing podspec file has only specified the version as 1.0 which doesn't work with Swift 3.

In the README it's mentioned that the project is at v3.1.1. Any reason why the podspec isn't updated?

**Comment by CrazyWisdom** [comment]
@Isuru-Nanayakkara 

```
➜  Example git:(master) cat Podfile
platform :ios, 9.0
use_frameworks!

target 'Example' do
    pod 'CocoaMQTT', '~>1.0.11'
end


➜  Example git:(master) pod --version
1.1.0.rc.2
➜  Example git:(master) 

```

**Comment by Isuru-Nanayakkara** [comment]
Got it! Thanks!
