### ISSUE TITLE
Would you please add a reconnect function after disconnect from server? 

### ISSUE THREAD

**Issue by hry625** [emqtt/CocoaMQTT#121]
I managed to do reconnect myself, but I think it would be better to have an auto-reconnect function in the lib. :-)

**Comment by dimohamdy** [comment]
@hry625  did you make it  ?

**Comment by hry625** [comment]
I just call mqtt.connect in the func mqttDidDisconnect(). So after a short delay(same as your keep alive period), it will try to reconnect to the broker

**Comment by alexyu1989** [comment]
Done. https://github.com/emqtt/CocoaMQTT/commit/63cd3983e8f20529ef1b80af1fc287033a738079
