### ISSUE TITLE
Since Swift 3, No longer receiving messages on subscribed channels

### ISSUE THREAD

**Issue by Spilly** [emqtt/CocoaMQTT#122]
I have two applications, one that is Swift 2.2 the other that is Swift 3, with each using CocoaMQTT. Using the same client setup between the two and the same mqtt broker, I am able to successfully connect, subscribe and ping/pong the broker, but only on the Swift 2.2 application am I receiving the messages coming from the broker.

Any ideas?

**Comment by dimohamdy** [comment]
@Spilly  any update about this issue

**Comment by dimohamdy** [comment]
i know this issue 
you can't make  subscribe after connect direct
like 
```
      mqttSetting()
      mqtt?.connect()
      mqtt?.subscribe("Sport", qos: .qos1)
      mqtt?.publish("Sport", withString: "Hello Sport", qos: .qos1, retained: false, dup: false)
```
you must wait to  didConnectAck ack: CocoaMQTTConnAck) and here you can make subscribe for topic

```
    func mqtt(_ mqtt: CocoaMQTT, didConnectAck ack: CocoaMQTTConnAck) {
        print("didConnectAck: \(ack)，rawValue: \(ack.rawValue)")
        if ack == .accept {
            mqtt.subscribe("chat/room/animals/client/+", qos: CocoaMQTTQOS.qos1)
        }
    }
```

**Comment by Spilly** [comment]
Thanks for the suggestion. Unfortunately I am waiting until the ack before calling subscribe. I have my own delegate I've implemented that gets called from the ack method and that then goes on to subscribe. I'm getting the successful subscription callback, just not any messages on the channel.

**Comment by dimohamdy** [comment]
i think it will be good if using closure

**Comment by hry625** [comment]
I guess the topic you sub may be different from the one you publish. Try to check if the topic is exactly identical, e.g. "/", capitalization and etc. Because you got a successful subscription callback.

**Comment by Spilly** [comment]
Double checked that they are identical. The topic is returned from the server and I verified that what the subscription ack sends me is the same as what I'm getting from the server.

**Comment by hry625** [comment]
That is really strange, cause you can get successful sub callback which means you sub to the topic.  You may use a pc/mac based mqtt client like "mqtt spy " to test if you can get expected payload from the topic. I am using swift 3 on my simple project, cocoa mqtt work just fine for me.

**Comment by alexyu1989** [comment]
@Spilly have you fix it now?
