### ISSUE TITLE
tvOS support?

### ISSUE THREAD

**Issue by tricaricom** [emqtt/CocoaMQTT#129]
I get this error when trying to use CocoaMQTT with a tvOS app:

**tvOS:  The platform of the target 'MY_TVOS_PROJECT' (tvOS 10.1) is not compatible with 'CocoaMQTT (1.0.11)', which does not support 'tvos'**

I see instructions for Carthage/tvOS but not Cocoapods/tvOS.

I am using CocoaPods 1.2.0

Thanks!

**Comment by alexyu1989** [comment]
@tricaricom Done. Please wait for the next release.
