### ISSUE TITLE
SSL truncated topic and payload message

### ISSUE THREAD

**Issue by szappanyos** [emqtt/CocoaMQTT#138]
The truncated topic continues into the message.
Example:
topic: heating_system/switch/status
payload: 0

I receive:
topic: heating_sy
payload: em/switch/status0

This all worked with an earlier version where secureMQTT was to config.

**Comment by alexyu1989** [comment]
@szappanyos Sorry about that. I made a stupid mistake: forget to delete my debug code. 
**Please update pod to 1.0.14.**
