### ISSUE TITLE
 CocoaMQTTFrameBuffer is not thread safe, may crash(array out of range)

### ISSUE THREAD

**Issue by AlvinZheng** [emqtt/CocoaMQTT#141]
in class CocoaMQTTFrameBuffer
       // take out the earliest frame
        let frame = buffer.remove(at: 0)

crash at here, when buffer has no element.

**Comment by alexyu1989** [comment]
```
var isBufferEmpty: Bool { get { return buffer.count == 0 }}
...
if isBufferEmpty || isSilosFull { return }
        // take out the earliest frame
        let frame = buffer.remove(at: 0)
```

This is weird. 
You can see the code above: If the buffer is empty, it will return anyway. And if buffer is not empty, the index-0 element should exist. Can you show more information about this? like crash stack or something. Thanks!

**Comment by AlvinZheng** [comment]
I publish message at globle queue, maybe the CocoaMQTTFrameBuffer is not thread safe? so, I can only publish message at main queue?

**Comment by alexyu1989** [comment]
@AlvinZheng I think you're right, it's not thread safe. I'm working on it.

**Comment by alexyu1989** [comment]
@AlvinZheng Sorry for a long time waiting. Do you publish message on only one queue or more than 2 queue?

**Comment by alexyu1989** [comment]
@AlvinZheng Can you send message on only 1 queue? If so, the buffer is not necessary to be thread safe. And the issue won't be fixed.

**Comment by alexyu1989** [comment]
@AlvinZheng Bug find and fixed. Please update CocoaMQTT to 1.0.18. Sorry for a long time waiting.

**Comment by AlvinZheng** [comment]
nice work!
