### ISSUE TITLE
Secure connection

### ISSUE THREAD

**Issue by tricaricom** [emqtt/CocoaMQTT#143]
Does the CocoaMQTT library require any type of server certificate when connecting on a secure port?

**Comment by alexyu1989** [comment]
1. One-way certification

No certificate is required locally. If you want to trust all untrust CA certificates, you can do this:

`mqtt.allowUntrustCACert = true`

1. Two-way certification
Need a .p12 file which is generated by a public key file and a private key file. You can generate the p12 file in the terminal:

`openssl pkcs12 -export -clcerts -in client-cert.pem -inkey client-key.pem -out client.p12`
