### ISSUE TITLE
isConnected ?? Check connection

### ISSUE THREAD

**Issue by fabiosoft** [emqtt/CocoaMQTT#146]
How can i check if client is already connected or not?

**Comment by terry-xiaoyu** [comment]
If you don't want any of your messages got lost in case of connection lost, I suggest you set an appropriate  keepalive parameter when connecting to the MQTT broker, and set the right qos when subscribing your topics, as well as the qos publishing your messages, instead of QoS 0.

**Comment by alexyu1989** [comment]
@fabiosoft Please check all the CocoaMQTT class' APIs first.

> open class CocoaMQTT {
>     open var connState
> }
