### ISSUE TITLE
断线重连之后可以接收上次连接发送给我的消息，但是没办法收到此时发送给我的消息，需要等到下次连接才可以收到

### ISSUE THREAD

**Issue by max321** [emqtt/CocoaMQTT#150]
您好，我有一个问题，就是cleansession设置为false，然后一开始都是发消息、接收消息都是正常的，也可以接收离线消息，但是不知道为什么，项目运行了多次之后，每次发消息都是正常的，但是就是接收不到消息，最重点的是我断开网络并且设置重连之后我订阅的主题的消息一下子都能收到，然后接下来订阅主题的消息又不能收到，需要下次连接上才能收到

**Comment by max321** [comment]
在你的demo里面 example这个项目中测试也发现这个问题。
具体步骤就是设置cleansession为false，clientID为一个固定值，大概项目跑个十几遍吧 然后偶然不确定的时间内就会出现接收不到消息，然后下次登录一次性拿到

**Comment by max321** [comment]
并且topic只订阅一次

**Comment by max321** [comment]
这个bug很严重，因为这样的话，我们整个项目就用不了你的这个库了

**Comment by alexyu1989** [comment]
@max321 收到了你的消息，我马上查看下怎么回事。带来的问题非常抱歉。

**Comment by alexyu1989** [comment]
@max321 方便加一下您的微信吗？

**Comment by max321** [comment]
答案就是 需要每次连接都订阅，因为订阅是有时效性的
