### ISSUE TITLE
CocoaMQTTWill value [object Object] 

### ISSUE THREAD

**Issue by daiwud** [emqtt/CocoaMQTT#153]
Good afternoon. When I send a message via CocoaMQTTWill, I get the value [object Object] instead of my message that I sent.
Someone can help or suggest what is the reason? In programming on swift novices.

**Comment by daiwud** [comment]
let clientID = "CocoaMQTT_test"
        let mqtt = CocoaMQTT(clientID: clientID, host: "222222.com", port: 8883)
        mqtt.username = "222"
        mqtt.password = "333"
        mqtt.willMessage = CocoaMQTTWill(topic: "/test", message: "1234")
        mqtt.keepAlive = 60
        mqtt.delegate = self
        mqtt.enableSSL = true
        
        mqtt.connect()

------------------------------
return in file type string "test" -> value [object Object]

**Comment by alexyu1989** [comment]
Sorry for a late reply:
I've tested the will message. It works well. The other client can receive the will message correctly.
Can you show more details? And what do you mean of "return in file type string "test" -> value [object Object]"?
