### ISSUE TITLE
successful subscribe should return the message sent by publisher

### ISSUE THREAD

**Issue by wajdan846** [emqtt/CocoaMQTT#155]
add another return value in delegate

**Comment by alexyu1989** [comment]
? I don't understand. Can you describe it with more detail?

**Comment by wajdan846** [comment]
sure, 
this function in the delegate 
           func subscribe(_ topic: String, qos: CocoaMQTTQOS) -> UInt16

is not providing the complete functionality (in my opinion) i.e when a client subscribes to a topic , then it is done in order to recieve a message (e.g a string) from the publisher. e.g we have an IoT system where we would like to turn on and off the lights and maintain manual changes in our app. So the ios app (after connecting) will publish a message 
using this 

         func publish(_ message: CocoaMQTTMessage) -> UInt16


(switch on) on a topic (Home/lights/light1) and this topic will be subscribed in the backend of a hardware (e.g a raspberry pi / odroid) and after subscribing , it should be able to recieve the "switch on" message..Similarly when the switches are turned off manually , the hardware will publish "switch off" on the same topic "Home/lights/light" and our ios app will subscribe to it but HERE IS THE PROBLEM.how will this app recieve the message "switch off" that it subscribed for.as the function in the delegate doesnot return a string i.e the message in that topic

Now I might be missing something here but if not its worth mentioning

**Comment by alexyu1989** [comment]
All you need is **CocoaMQTTDelegate protocol**.

- **How to know if the client subscribes a topic successful?**
```
func mqtt(_ mqtt: CocoaMQTT, didSubscribeTopic topic: String)
```

- **How to know if a message was published successfully?**
```
// for qos 1
func mqtt(_ mqtt: CocoaMQTT, didPublishAck id: UInt16)
// for qos 2
func mqtt(_ mqtt: CocoaMQTT, didPublishComplete id: UInt16)
```

- **How to receive message from a subscribed topic?**
```
func mqtt(_ mqtt: CocoaMQTT, didReceiveMessage message: CocoaMQTTMessage, id: UInt16 )
```

**Comment by wajdan846** [comment]
pardons for the confusion. I see this is the solution

`func mqtt(_ mqtt: CocoaMQTT, didReceiveMessage message: CocoaMQTTMessage, id: UInt16 )`

thanks

**Comment by alexyu1989** [comment]
You're welcome! The `id` is used to distinguish the messages.
