### ISSUE TITLE
Is publish or subscribe required in the didConnectAck delegate?

### ISSUE THREAD

**Issue by JiaGuoWMU** [emqtt/CocoaMQTT#156]
In my application, I only need to publish to the server, but with no need to subscribe any topic. The question is do I have to publish or subscribe something in the delegate method `func mqtt(mqtt: CocoaMQTT, didConnectAck ack: CocoaMQTTConnAck) {}` ? Because I noticed only if I publish message in the above method, it is successful. How can I keep publishing messages, for example, every 5 sec? Is there anyway to wait after calling connect() method until the connection is accepted by the server? For example:

`mqtt!.connect()`
`waiting for ack signal...`
`mqtt!.publish(...)`

**Comment by alexyu1989** [comment]
You are right. Actions should do after connecting success.

**Comment by JiaGuoWMU** [comment]
If I don't want to publish message in the delegate method `func mqtt(mqtt: CocoaMQTT, didConnectAck ack: CocoaMQTTConnAck) {}`, how am I able to know the connection is successful?

**Comment by alexyu1989** [comment]
mqtt.connState == connected

**Comment by JiaGuoWMU** [comment]
@alexyu1989 Thanks. So, can I use the loop to check the connection? For example:
`while mqtt.connState != connected {`
`      // do nothing`
`}`
`mqtt.publish(...)`

**Comment by alexyu1989** [comment]
I don't think this is a good way. 
If you want to publish message immediately after mqtt connected. Put it in the delegate method `func mqtt(mqtt: CocoaMQTT, didConnectAck ack: CocoaMQTTConnAck) {}` is a better idea.
