### ISSUE TITLE
can use certification?

### ISSUE THREAD

**Issue by isunimp** [emqtt/CocoaMQTT#157]

**Comment by alexyu1989** [comment]
Yes. 
Ref: https://github.com/emqtt/CocoaMQTT#ssl-secure

**Comment by isunimp** [comment]
must generate the p12 ? but I got the certificate without a private key，broker technician says no need to verify the private key。

**Comment by alexyu1989** [comment]
You can use one-way certification:
No certificate is required locally. If you want to trust all untrust CA certificates, you can do this:
`mqtt.allowUntrustCACert = true`

(p12 is for 2-way certi)

**Comment by isunimp** [comment]
so perfect mqtt client, thank you

**Comment by alexyu1989** [comment]
Happy to hear that. Enjoy!
