### ISSUE TITLE
Bulk subscribe

### ISSUE THREAD

**Issue by kkapitan** [emqtt/CocoaMQTT#158]
Hi, I have a question - is CocoaMQTT by any chance supporting bulk subscriptions? I was not able to check this by myself unfortunately. 

Thank you

**Comment by alexyu1989** [comment]
Sorry, there is no API for bulk subscriptions. You can use a for-loop to subscribe topics instead.

**Comment by kkapitan** [comment]
Ok, thank you for the answer and for this amazing library :) I'm going to close the issue then

**Comment by alexyu1989** [comment]
Happy to hear that. Enjoy it!   : )
