### ISSUE TITLE
How to identify publish acknowledgement is specific to a event?

### ISSUE THREAD

**Issue by SanyasiraoM** [emqtt/CocoaMQTT#159]
Example: 
I published "This is message1", "This is message2"

So how to know whether my "This is message1" is publish success or not?

**Comment by SanyasiraoM** [comment]
@alexyu1989 Can you look into this?

**Comment by HJianBo** [comment]
@SanyasiraoM Sorry about tooooo late reply :(

On the current version (1.0.19), you can get a PacketId when publish a message. And, it will be passed back by callback functions

The code logic may be:
```swift
// ...

let pktId0 = mqtt.publish(topic, withString: message, qos: .qos0)
let pktId1 = mqtt.publish(topic, withString: message, qos: .qos1)
let pktId2 = mqtt.publish(topic, withString: message, qos: .qos2)

// ...

// when some message has been sent by socket, this func will be called
func mqtt(_ mqtt: CocoaMQTT, didPublishMessage message: CocoaMQTTMessage, id: UInt16) {
     // will be called 3 times
    print("message id: \(id) did publish")
}
```

**Comment by SanyasiraoM** [comment]
Thank you @HJianBo.
