### ISSUE TITLE
How to know why the disconnect method got called?

### ISSUE THREAD

**Issue by SanyasiraoM** [emqtt/CocoaMQTT#161]
How to know why the disconnect method got called?

Whether it's initiated by the user or by internet loss or something else?

**Comment by HJianBo** [comment]
@SanyasiraoM When the connection has disconnected or broken, the callback named `mqttDidDisconnect(_ mqtt: CocoaMQTT, withError err: Error?)` will be called.

The argument named `err: Error?` showed the disconnection reason; it will be `nil` if you called `disconnect` method.

**Comment by SanyasiraoM** [comment]
Thank you @HJianBo @emqplus.
