### ISSUE TITLE
Certificate with PEM format

### ISSUE THREAD

**Issue by chauchinyiu** [emqtt/CocoaMQTT#166]
Hello ,

  I need to communicate with my server which have SSL-pinning and which they give me a pem file. However i dont know how to use it with your framework . Could you please let me know to use it with your framework? thanks a lot!

regards
chinyiu

**Comment by HJianBo** [comment]
@chauchinyiu You can reference the Example project

https://github.com/emqtt/CocoaMQTT/blob/e8081f3fd64a64f176cf07369eacf738bd6a5d35/Example/Example/ViewController.swift#L65-L81

**Comment by HJianBo** [comment]
Close the issue! If you are in doubt still, reopen it!
