### ISSUE TITLE
have memory leak

### ISSUE THREAD

**Issue by isunimp** [emqtt/CocoaMQTT#168]
<img width="674" alt="wx20170907-115523 2x" src="https://user-images.githubusercontent.com/7866141/30145376-77694f4e-93c3-11e7-95c6-a902a4a1c0aa.png">
<img width="676" alt="wx20170907-115515 2x" src="https://user-images.githubusercontent.com/7866141/30145373-774b2640-93c3-11e7-9be8-e8358bdc9881.png">
<img width="683" alt="wx20170907-115504 2x" src="https://user-images.githubusercontent.com/7866141/30145374-77589fc8-93c3-11e7-9d5d-2c350bdcc358.png">
<img width="681" alt="wx20170907-115445 2x" src="https://user-images.githubusercontent.com/7866141/30145375-775b55ec-93c3-11e7-859f-b8da75565a93.png">

**Comment by KieranLafferty** [comment]
Also seeing this memory leak

**Comment by HJianBo** [comment]
Fixed at v1.0.20
