### ISSUE TITLE
Swift4 support?

### ISSUE THREAD

**Issue by jinfagang** [emqtt/CocoaMQTT#170]
Since XCode9 has been release for a while time, should upgrade all the project into swift4 to catch up with the newest api changes in swift?

**Comment by emqplus** [comment]
@CrazyWisdom Please make a plan to upgrade the library to Swift4

**Comment by Marcello168** [comment]
Please make a plan to upgrade the library to Swift4

**Comment by HJianBo** [comment]
Hi, @Marcello168 The new version supported swift 4 has published!

Thanks for your attention!
