### ISSUE TITLE
Unable to Connect() to mqtt

### ISSUE THREAD

**Issue by chikiball** [emqtt/CocoaMQTT#172]
Currently using xCode 9.0 (9A235) iOS 11.02

I wrote a simple application to test the library.

```
override func viewDidLoad() {
        super.viewDidLoad()
        willTopic = "/Topic"
        
        let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
        let mqtt = CocoaMQTT(clientID: clientID, host: "localhost", port: 1883)
        mqtt.username = "abc"
        mqtt.password = "mqttABC"
        mqtt.willMessage = CocoaMQTTWill(topic: willTopic, message: "offline")
        mqtt.willMessage?.retained = true
        mqtt.keepAlive = 15
        mqtt.delegate = self
        mqtt.enableSSL = true
        
        mqtt.connect()
    }
```

delegate function didConnect and didConnectAck Never get called.

**Comment by bigbearlazier** [comment]
Same here. 
Delegate method `mqtt(_ mqtt: CocoaMQTT, didConnect host: String, port: Int)` never gets called.

Xcode Version 9.1 (9B55)
CocoaMQTT 1.0.19

And it works well after I fallback to 1.0.11(my previous using version) without changing any codes.

**Comment by HJianBo** [comment]
@chikiball @bigbearlazier 
There is really a problem with establishing SSL connections :(
In

**Comment by madtocc** [comment]
I have the same issue. I was using the library around October and right now I don't receive the didConnect. I have checked the broker and there's a connection stablished between the client and the broker. The only message that I'm receiving is when it disconnect from the broker (func mqttDidDisconnect)

**Comment by a-athaullah** [comment]
@chikiball,  you can fix it by put mqtt to class property:

`
var mqtt:CocoaMQTT?

override func viewDidLoad() {
        super.viewDidLoad()
        willTopic = "/Topic"
        
        let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
        mqtt = CocoaMQTT(clientID: clientID, host: "localhost", port: 1883)
        mqtt.username = "abc"
        mqtt.password = "mqttABC"
        mqtt.willMessage = CocoaMQTTWill(topic: willTopic, message: "offline")
        mqtt.willMessage?.retained = true
        mqtt.keepAlive = 15
        mqtt.delegate = self
        mqtt.enableSSL = true
        
        mqtt.connect()
    }
`
And it will work
I allready create PR to this issues https://github.com/emqtt/CocoaMQTT/pull/180 so you dont need to do that

**Comment by HJianBo** [comment]
I think the basic reason is the variable 'mqtt' is local variables in `viewDidLoad()` function scope

```swift
let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
let mqtt = CocoaMQTT(clientID: clientID, host: "localhost", port: 1883)
```
**This is bad practice**! The CocoaMQTT instance must be a global variable or being a property of some class, not a local variable

So, close this issue now.

**Comment by andy1247008998** [comment]
> var mqtt:CocoaMQTT?

You saved my life.

**Comment by andy1247008998** [comment]
> I think the basic reason is the variable 'mqtt' is local variables in the `viewDidLoad()` function scope:
> 
> ```swift
> let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
> let mqtt = CocoaMQTT(clientID: clientID, host: "localhost", port: 1883)
> ```
> 
> **This is bad practice**! The CocoaMQTT instance must be a global variable or being a property of some class, not a local variable
> 
> So, close this issue now.

You should definitely update the document.
