### ISSUE TITLE
Possible memory leak between CocoaMQTT and CocoaMQTTReader ?

### ISSUE THREAD

**Issue by alex-chan** [emqtt/CocoaMQTT#175]
Hi, I'm much grateful about this excellent library, it helps me a lot.

But I have a question about the source code:
class `CocoaMQTT` holds a variable named `reader`, which is an instance of `CocoaMQTTReader`
, however , in function `CocoaMQTT.connect`, it set the delegate to `CocoaMQTT`. 

It will cause circle reference, will it? Thank you!

https://github.com/emqtt/CocoaMQTT/blob/e8081f3fd64a64f176cf07369eacf738bd6a5d35/Source/CocoaMQTT.swift#L250-L252

https://github.com/emqtt/CocoaMQTT/blob/e8081f3fd64a64f176cf07369eacf738bd6a5d35/Source/CocoaMQTT.swift#L530-L541

**Comment by HJianBo** [comment]
@alex-chan Yes, it will :( 
It has fixed on dev branch. we will release as next version!

**Comment by HJianBo** [comment]
The issue fixed at v1.0.20. Close it now.
