### ISSUE TITLE
Using master via Carthage no longer builds.

### ISSUE THREAD

**Issue by bmatthys** [emqtt/CocoaMQTT#179]
Since the changes done on January 14th, the project no longer builds, used via Carthage. It can be fixed by doing after a `carthage update` performing a `pod install` in the CocoaMQTT checkout folder. But this can't be the way to do it final.

**Comment by HJianBo** [comment]
Hi, @bmatthys Sorry for producing an incompatible modify.

I will fix it as quickly as possible

**Comment by HJianBo** [comment]
@bmatthys The hotfix version 1.1.1 has published! Thanks for your attention!

**Comment by bmatthys** [comment]
There is also another small issue, @HJianBo , when I tried to upload my application to iTunes Connect with your project included via Carthage I kept on getting a reject on the `CFBundleShortVersionString`. You can't use a '1.1-beta.1' or something like that. It should be something like 1.1.1.

**Comment by HJianBo** [comment]
Hi @bmatthys
I have re-published this version(1.1.1) and fixed the invalid bundle version! :]
