### ISSUE TITLE
Reconnect then CANNOT subscribe to topic

### ISSUE THREAD

**Issue by dubiao** [emqtt/CocoaMQTT#181]
At first, I can connect to my server, and I can subscribe to any topic, and get message correctly

Then I called `unsubscribe()`  and  `disconnect() ` get ` mqtt(_:, DidDisconnect)` called

Then I called `connect() ` and  get `mqtt(_:, didConnectAck: )` called
Then I called `subscribe("topic")` but `mqtt(: didSubscribeTopic:)`  not called 

No error occurred.

**Comment by HJianBo** [comment]
Hi, @dubiao Sorry late reply. I can't reproduce this issue. The `mqtt(_:, didSubscribeTopic:)` will be called every time

Could you please provide more details information?

**Comment by HJianBo** [comment]
Close the issue.

If you are in doubt still, reopen it!
