### ISSUE TITLE
Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer

### ISSUE THREAD

**Issue by Bassyouni** [emqtt/CocoaMQTT#183]
Every time it connects , it disconnects immediately and shows up this error. here is my code
` mqtt = Mqtt(url: "xx.xxx.xx.xxx", port: 1883)`
       ` mqtt.keepAlive = 60`
        `mqtt.delegate = self`
       ` _ = mqtt.connect()`

**Comment by HJianBo** [comment]
It seems the server closed this connection!

Could you please provide more details for analyzing this error? (i.e: More clearly code etc.)

**Comment by Bassyouni** [comment]
this are the delegets 
`func mqtt(_ mqtt: CocoaMQTT, didConnect host: String, port: Int)
    {
        print("connected to host: \(host) on port: \(port)")
    }
   
    func mqtt(_ mqtt: CocoaMQTT, didConnectAck ack: CocoaMQTTConnAck)
    {
        print("connection ack")
    }
    func mqtt(_ mqtt: CocoaMQTT, didPublishMessage message: CocoaMQTTMessage, id: UInt16)
    {
        print("published")
    }
    func mqtt(_ mqtt: CocoaMQTT, didPublishAck id: UInt16)
    {
        print("publish ack")
    }
    func mqtt(_ mqtt: CocoaMQTT, didReceiveMessage message: CocoaMQTTMessage, id: UInt16 )
    {
        print("recived message: \(message.string ?? message.topic)")
    }
    func mqtt(_ mqtt: CocoaMQTT, didSubscribeTopic topic: String)
    {
        print("subscribed")
    }
    func mqtt(_ mqtt: CocoaMQTT, didUnsubscribeTopic topic: String)
    {
        print("unsuscribed")
    }
    func mqttDidPing(_ mqtt: CocoaMQTT)
    {
        print("ping")
    }
    func mqttDidReceivePong(_ mqtt: CocoaMQTT)
    {
        print("pong")
    }
    func mqttDidDisconnect(_ mqtt: CocoaMQTT, withError err: Error?)
    {
        print("disconnected: \(err.debugDescription)")
        Timer.after(5.seconds) {
            _ = self.mqtt.connect()
        }
    }`

this is the error coming in console
`connected to host: 54.244.99.193 on port: 1883
disconnected: Optional(Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer})

connected to host: 54.244.99.193 on port: 1883
disconnected: Optional(Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" `

There is nothing more to it. except my wrapper class and here is it
`class Mqtt
{
    //MARK:- variables
    private static var _mqtt: CocoaMQTT!
    private var _delegate: CocoaMQTTDelegate!
    
    
    //MARK:- Constructors & destructors
    private func constructor(url:String , port:UInt16)
    {
        if Mqtt._mqtt == nil
        {
            let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
            Mqtt._mqtt = CocoaMQTT(clientID: clientID, host: url, port: port)
            Mqtt._mqtt.willMessage = CocoaMQTTWill(topic: "/will", message: "dieout")
            Mqtt._mqtt.allowUntrustCACertificate = true
        }
        

    }
    
    init()
    {
        let url = "192.168.1.10"
        constructor(url: url, port: 1883)
    }
    
    init(url:String)
    {
        constructor(url: url, port: 1883)
    }
    
    init(url:String, port:UInt16)
    {
        constructor(url: url, port: port)
    }
    
    deinit
    {
        Mqtt._mqtt.disconnect()
    }

    
    //MARK:- public functions
    public func connect() -> Bool
    {
        return Mqtt._mqtt.connect()
    }
    
    public func subscribe(toTopic:String) -> Bool
    {
        if toTopic  != ""
        {
            Mqtt._mqtt.subscribe(toTopic)
            return true
        }
        else
        {
            return false
        }
    }
    
    public func unSuscribe(toTopic:String) -> Bool
    {
        if  toTopic != ""
        {
            Mqtt._mqtt.unsubscribe(toTopic)
            return true
        }
        else
        {
            return false
        }
    }
    
    public func publish(message:String , topic:String) -> Bool
    {
        if  message != "" && topic  != ""
        {
            Mqtt._mqtt.publish(topic, withString: message)
            return true
        }
        else
        {
            return false
        }
    }
    
    public func disconnect()
    {
        Mqtt._mqtt.disconnect()
    }
    
    
    //MARK:- public Varibales
    
    var delegate: CocoaMQTTDelegate {
        set { Mqtt._mqtt.delegate = newValue }
        get { return Mqtt._mqtt.delegate! }
    }
    
    var keepAlive: UInt16 {
        set { Mqtt._mqtt.keepAlive = newValue }
        get { return Mqtt._mqtt.keepAlive }
    }
    
    var cleanSession: Bool {
        set { Mqtt._mqtt.cleanSession = newValue }
        get { return Mqtt._mqtt.cleanSession }
    }

}
`

**Comment by Bassyouni** [comment]
Issue solved, the installed mosquito on Ubuntu was version 0.15 which is not the latest and uses an outdated protocol version. I updated mosquitto on Ubuntu to 1.4 (latest). And it worked.

**Comment by vadlani9** [comment]
I got the same error when i try to use 1885 port numer.

I have added below code in my existing code:
```
mqttReference?.dispatchQueue = DispatchQueue.global(qos: .userInitiated)
        //mqttReference?.logLevel = .debug
        mqttReference?.enableSSL = true
        mqttReference?.sslSettings = [
            GCDAsyncSocketManuallyEvaluateTrust: NSNumber(booleanLiteral: true),
            GCDAsyncSocketUseCFStreamForTLS: NSNumber(booleanLiteral: false),
            kCFStreamSSLPeerName as String: "" as NSString,
            GCDAsyncSocketSSLProtocolVersionMin: NSNumber(integerLiteral: Int(SSLProtocol.tlsProtocol1.rawValue)),
            GCDAsyncSocketSSLProtocolVersionMax: NSNumber(integerLiteral: Int(SSLProtocol.tlsProtocol12.rawValue)),
        ]
```
        
My complete code now:

/```
/  let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
        mqttReference = CocoaMQTT(clientID: "", host: mqttProfile.baseURL, port: UInt16(mqttProfile.port))
        mqttReference?.username = mqttProfile.userName
        mqttReference?.password = mqttProfile.password
        mqttReference?.allowUntrustCACertificate = true
        
        
        mqttReference?.dispatchQueue = DispatchQueue.global(qos: .userInitiated)
        //mqttReference?.logLevel = .debug
        mqttReference?.enableSSL = true
        mqttReference?.sslSettings = [
            GCDAsyncSocketManuallyEvaluateTrust: NSNumber(booleanLiteral: true),
            GCDAsyncSocketUseCFStreamForTLS: NSNumber(booleanLiteral: false),
            kCFStreamSSLPeerName as String: "" as NSString,
            GCDAsyncSocketSSLProtocolVersionMin: NSNumber(integerLiteral: Int(SSLProtocol.tlsProtocol1.rawValue)),
            GCDAsyncSocketSSLProtocolVersionMax: NSNumber(integerLiteral: Int(SSLProtocol.tlsProtocol12.rawValue)),
        ]
        
        
        mqttReference?.autoReconnect = true
        mqttReference?.backgroundOnSocket = mqttProfile.allowBackgroundMQTT
        mqttReference?.delegate = self
        do {
            if((mqttReference?.connect())!){
               ...........

```

Now it's working fine.
