### ISSUE TITLE
"[!] CocoaMQTT has been deprecated"  after pod install

### ISSUE THREAD

**Issue by jiaopen** [emqtt/CocoaMQTT#185]
![image](https://user-images.githubusercontent.com/8399918/36085372-53603b94-1000-11e8-8a9d-7925c0caf7da.png)

**Comment by HJianBo** [comment]
What version is CocoaMQTT configured?

**Comment by jiaopen** [comment]
pod 'CocoaMQTT'
I didn't specify the version in podfile.

**Comment by HJianBo** [comment]
Hi, @jiaopen Has fixed it.

This warning is due to a minor mistake operation while pushing the CocoaPods package. Thanks a lot!
