### ISSUE TITLE
I want to send to data(hex byte array)

### ISSUE THREAD

**Issue by sunghwan523** [emqtt/CocoaMQTT#187]
I received string on the mobile(iphone)

string - ABCDEF

i want to send to mqtt server as 0xAB, 0xCD, 0xEF
but it is 41,42,43,44,45,46 => string to hex

i want to change hex string to hex byte array(data?)

but cocoamqtt publish is only string.....

how to change that?

**Comment by HJianBo** [comment]
Hi, @sunghwan523 The `CocoaMQTT` has provided a interface to do it:
https://github.com/emqtt/CocoaMQTT/blob/fddfa866f6e786585dd3938c2c47a270f853a7f2/Source/CocoaMQTT.swift#L341-L343

Use it as the following example code:
```swift
var message = CocoaMQTTMessage(topic: topic, payload: [0xAC, 0xCD, 0xEF], qos: .qos0, retained: false, dup: false)

mqttclient.publish(message)
```

**Comment by sunghwan523** [comment]
Thank you. I solved the problem.
