### ISSUE TITLE
Dependency CocoaAsyncSocket need to update to 7.6.3

### ISSUE THREAD

**Issue by nok6583** [emqtt/CocoaMQTT#193]
Using the last version (1.1.1) of CocoaMQTT require to use the version 7.6.2 of CocoaAsyncSocket pod.   But this version have to much warning (more 250 warnings) with the last version of xcode. Is it possible to make a new release with 7.6.3 version of CocoaAsyncSocket pod ?

**Comment by HJianBo** [comment]
This issue has fixed and published at v1.1.2. Thanks for your contribution!

**Comment by nok6583** [comment]
Great HJianBo and thank you for your reactivity ;)
