### ISSUE TITLE
How can i subscrib a new topic, when mqtt is conecting?

### ISSUE THREAD

**Issue by JoshuaFeng5** [emqtt/CocoaMQTT#197]
I just  " mqtt.subscribe("VirtualTopic.pm." + topic, qos: CocoaMQTTQOS.qos0)"
but it seams does`t work

**Comment by HJianBo** [comment]
You should subscribe any topics when connect successful (means: connack equal .accept).

See Example project(Line 144-145):
https://github.com/emqtt/CocoaMQTT/blob/b24b9a999cc939eb6d33f37a17a692c5cba4442c/Example/Example/ViewController.swift#L141-L151
