### ISSUE TITLE
Mqtt connection error

### ISSUE THREAD

**Issue by yusufonderd** [emqtt/CocoaMQTT#199]
I'm getting this error when trying connect mqtt.

_Error Domain=kCFStreamErrorDomainNetDB Code=8 "nodename nor servname provided, or not known" UserInfo={NSLocalizedDescription=nodename nor servname provided, or not known}_
               

             
   ```
                let subscriptionTopic = "positions/latest";
                let mqtt = CocoaMQTT(clientID: clientID, host: websocketUrl, port: 1883)
                mqtt.allowUntrustCACertificate = true
                mqtt.willMessage = CocoaMQTTWill(topic: subscriptionTopic, message: "dieout")
                mqtt.keepAlive = 60
                mqtt.delegate = self
                mqtt.connect()
```

**Comment by HJianBo** [comment]
The current version (1.1.2) not support Websocket MQTT broker server. Please using it over TCP backend.

**Comment by yusufonderd** [comment]
Is there a library you can recommend?

**Comment by HJianBo** [comment]
Sorry that, The mostly iOS native framework support TCP connection only
