### ISSUE TITLE
rror Domain=GCDAsyncSocketErrorDomain

### ISSUE THREAD

**Issue by jelordreygulle** [emqtt/CocoaMQTT#203]
Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}

**Comment by HJianBo** [comment]
This error is caused by Server closed Socket directly! Please make sure your Server allow the Client (username/password) connected.

If not, please provide more details information.
