### ISSUE TITLE
how can we set TLS 

### ISSUE THREAD

**Issue by jelordreygulle** [emqtt/CocoaMQTT#205]
is it possible to set TLS on this? i think that is the reason why the server is closing it.

**Comment by HJianBo** [comment]
Yes, it is possible. Whether the client need a TLS depends on the settings on your server side.

**Comment by jelordreygulle** [comment]
what does did received trust mean Sir ? does that mean that you were able to connect to the server?

**Comment by jelordreygulle** [comment]
And also when publishing a message i am receiving a response didPublishMessage: <CocoaMQTT.CocoaMQTTMessage: 0x1c4479f40> and 4 but my server is not receiving it. does that response mean that i was able to publish ? or there is a problem with the server?

**Comment by HJianBo** [comment]
What is QoS of the message?  When `didPublishMessage:` has been called, it does mean the message has published successfully. You can subscribe a same as Topic for checking it.

**Comment by jelordreygulle** [comment]
I have made it possible Already i subsribe and publish once 

 func mqtt(_ mqtt: CocoaMQTT, didConnectAck ack: CocoaMQTTConnAck) {
        print("didConnectAck: \(ack)，rawValue: \(ack.rawValue)")
        print("let ther be light:" , light)
        if ack == .accept {
  and then publish and subscribe

}
