### ISSUE TITLE
Add SSL/TLS Support

### ISSUE THREAD

**Issue by SkyMatt70** [emqtt/CocoaMQTT#21]

**Comment by knodeit** [comment]
Any planning on SSL support?

**Comment by erylee** [comment]
@knodeit, Yes. Working on this feature:)

**Comment by knodeit** [comment]
looking forward to it, if you need assistance in testing it out, please let me know available to help

**Comment by erylee** [comment]
@knodeit, @SkyMatt70. PR: https://github.com/emqtt/CocoaMQTT/pull/22

**Comment by knodeit** [comment]
Where to configure the SSL certificate? trying to test this but it's missing some documentation

**Comment by tethridge** [comment]
Any updates available for this issue?  I need SSL cert support too.

**Comment by CrazyWisdom** [comment]
@tethridge
https://github.com/emqtt/CocoaMQTT/issues/111
