### ISSUE TITLE
More explicit console log description

### ISSUE THREAD

**Issue by prwiley** [emqtt/CocoaMQTT#219]
Is there a way to turn off debug messages to console?

E.g. CocoaMQTT(debug): ping

**Comment by HJianBo** [comment]
Hi @prwiley sorry too late reply.

If you want to turn off it, just changing the log level of client, e.g:
```swift
// enum type with: debug, warning, error, off
client.logLevel = .off
```

**Comment by prwiley** [comment]
@HJianBo thanks! 

I also wonder if there is a explanation or description of each of the debug messages.
