### ISSUE TITLE
Able to Publish without didConnect callback ever running

### ISSUE THREAD

**Issue by phbprogramming** [emqtt/CocoaMQTT#226]
I have a function that runs on my didConnect callback to enable functionality of my app. However, the only function that runs when I connect to my Mosquitto server is DidConnectAck.

To be clear, in what situation should my didConnect callback be running? I am able to publish messages and subscribe to topics just fine on my implementation as is.

**Comment by HJianBo** [comment]
Hi, @phbprogramming Sorry to reply too late.

Yes, the `didConnect ` callback just means that the TCP connection was established successfully. Not an MQTT transport established. So you should perform PUBLISH operation after the `didConnectAck` called.

BTW, in the v1.1.0 version, we have removed the `didConnect` callback. So, after 1.1.0, we don't need to care about that, just using the `didConnectAck` callback function
