### ISSUE TITLE
Using client certificate and identity to connect with MQTT

### ISSUE THREAD

**Issue by manismku** [emqtt/CocoaMQTT#234]
Hi, 
I am receiving client key file (.key) and client certificate file (.cer) from server and runtime I need to connect to MQTT channel. But it seems we are need .p12 file in order to connect.

1. Is there any way we can create .p12 file programmatically in iOS?
2. OR, How can we use these two files .key and .cert to connect securely to MQTT?

Thanks,
Manish

**Comment by HJianBo** [comment]
Q1: The [post]( https://stackoverflow.com/questions/26883342/ios-how-to-create-pkcs12-p12-keystore-from-private-key-and-x509certificate-in) pointed out that

Q2: There are some functions for creating Cert with data. Unfortunately, I didn't find a detailed document about using them.

```swift
SecCertificateCreateWithData(_:_)
sec_identity_create_with_certificates(_:_)
```

Hope useful to you.

**Comment by manismku** [comment]
Yes. Correct. We compiled openssl now for iPhone and used same post to create P12 out of cert and key. It's now working for us.
