### ISSUE TITLE
CocoaMQTTReader.frameReady() EXC_BREAKPOINT

### ISSUE THREAD

**Issue by qhccthanh** [emqtt/CocoaMQTT#235]
https://github.com/emqtt/CocoaMQTT/blob/d386034adaf46842626f64781a6a622517f8c4c6/Source/CocoaMQTT.swift#L653

Should use guard let or if let when force unwraps frameType. 

``` swift 
 guard let frameType = CocoaMQTTFrameType(rawValue: UInt8(header & 0xF0)) else {
       return
}
```

**Comment by HJianBo** [comment]
Hi, @qhccthanh This line has fixed. Thanks for your contribution!
