### ISSUE TITLE
func mqtt(_ mqtt: CocoaMQTT, didPublishComplete id: UInt16) never triggered

### ISSUE THREAD

**Issue by tunctugcu** [emqtt/CocoaMQTT#236]
Hi,

I tried to be sure that the mqtt package is sent but the didPublishMessage method never triggered. 

And the `didPublishMessage` function is always called. Even the network is not there.

Is there a way to make sure the message is sent?

**Comment by HJianBo** [comment]
Hi, @tunctugcu Sorry for that, The ` mqtt(_ mqtt: CocoaMQTT, didPublishMessage message: CocoaMQTTMessage, id: UInt16)` will be called once you have called the publish function. (In fact, it just indicates that a message has added to send buffer, not sent or arrived peer success).

If you need to ensure some message has arrived, you can publish a message by Qos1 or Qos2 and verify with the `func mqtt(_ mqtt: CocoaMQTT, didPublishAck id: UInt16)` delegate

**Comment by tunctugcu** [comment]
Thanks for your help
