### ISSUE TITLE
How to publish Data(NsData) ?

### ISSUE THREAD

**Issue by smkumar84** [emqtt/CocoaMQTT#237]
I tried to publish string format working fine . But i want to publish NSData  . 
If possible method is here?  Please help me to resolve this
 

Ex:    // mqtt!.publish("/MqttBroker" , withString:(data?.toString())!)

**Comment by HJianBo** [comment]
Hi,@smkumar84 The CocoaMQTT's function `func publish(_ message: CocoaMQTTMessage) -> UInt16` may be helpful with you. 

Ex:
```swift
let message = CocoaMQTTMessage(topic: "topic", payload: [0x01,0x02])
mqtt.publish(message)
```

**Comment by smkumar84** [comment]
Thanks for your response. I have tried the same scheme and values in Java and iOS. I have used AVRO serialization 

From Java, it is working fine. but in ios some junk printing for long variables in server(4.1391354931527072e+17) .String eveything is working fine.


https://avro.apache.org

From java i'm getting this : 100:98100:1005050013:001(595bde931b0142cc9a14202.10225009bedc650xd650????

For iOS 100:98100:1005050013:001(595bde931b0142cc9a14202.10225009bedc65e0xd650¨¿


Sample scheme is 
const char schemaNEw[] =

"{\"type\" : \"record\","
    "\"name\" : \"location_data\","
    "\"namespace\" : \"com.example.student\","
    "\"fields\" : [ { "
        "\"name\" : \"emp_name\",\"type\" : \"string\"},"
        "{\"name\": \"address\",  \"type\": \"string\"},"
        "{\"name\": \"emp_phone\", \"type\": \"string\"},"
        "{\"name\": \"emp_id\", \"type\": \"string\"},"
        "{\"name\": \"emp_email\", \"type\": \"string\"},"
        "{\"name\": \"emp_firstname\", \"type\": \"string\"},"
        "{\"name\": \"emp_lastname\", \"type\": \"string\"},"
        "{\"name\": \"emp_dept\", \"type\": \"string\"},"
        "{\"name\": \"emp_salary\", \"type\": \"string\"},"
        "{\"name\": \"emp_exp\", \"type\": \"string\"},"
"{\"name\": \"time_stamp\", \"type\": \"long\",\"default\":55556}"
    "]"
"}";

**Comment by HJianBo** [comment]
Hi,@smkumar84 sorry for the late reply. Is the problem has resolved now? In my view, in the first, you should check whether the data received on the two platforms is matching?  Then, make sure the AVRO  parser of iOS is compatible with another platform.
