### ISSUE TITLE
Memory leak at CocoaMQTT.publish(topic, withString: message)

### ISSUE THREAD

**Issue by anuthomasc** [emqtt/CocoaMQTT#242]
Getting hundreds of memory leaks when calling this, 
func publish(_ topic: String, withString string: String, qos: CocoaMQTTQOS, retained: Bool, dup: Bool) -> UInt16

**Comment by HJianBo** [comment]
Hi,@anuthomasc Thanks for your report, and can you provide your CocoaMQTT version?

**Comment by anuthomasc** [comment]
CocoaMQTT (1.1.3)

**Comment by HJianBo** [comment]
Hi, @anuthomasc Sorry to reply so late!

I have fixed this bug and released in the v1.2.0! Thanks for your feedback this.
