### ISSUE TITLE
keepAlive and autoReconnect not working when socket delegate methods are called in a background queue

### ISSUE THREAD

**Issue by jmiltner** [emqtt/CocoaMQTT#245]
This is issue #151 re-emerging after commit e1e9817. I have created a patch for an alternative fix that uses dispatch timers instead of NSTimer. 
The code change might still need some cleanup, but I verified that it works, although I did not explicitly check for race conditions on connState read/writes. (However, given that with this change the timers actually run on the mqtt queue, I don't see this being an issue)

[CocoaMQTT-timers-on-background-queue.patch.zip](https://github.com/emqtt/CocoaMQTT/files/2768821/CocoaMQTT-timers-on-background-queue.patch.zip)

**Comment by HJianBo** [comment]
Hi, @jmiltner Thanks for your contribution. I'll check it later. Furthermore, could you commit a Pull Request in the future? It's may more convenience and efficiently :]

**Comment by jmiltner** [comment]
Thanks for considering.
Yes, I know I really should be using pull requests - I'll figure out how to do this ;-)

Thanks,
-jens

**Comment by jmiltner** [comment]
Added a pull request for this...
-jens

**Comment by jmiltner** [comment]
Any consideration of this fix? Do you need any additional information?

**Comment by HJianBo** [comment]
Hi, @jmiltner sorry too late response there, I'm very busy on the recent months.

And, I'll review this PR later. I'm very grateful for your contributions!

**Comment by HJianBo** [comment]
Hi, @jmiltner I have merged this RP and released it in the v1.2.0.

Thanks a lot of your contributions
