### ISSUE TITLE
How to add CocoaMqtt Manually

### ISSUE THREAD

**Issue by sharihv** [emqtt/CocoaMQTT#247]
I don't have GitHub access at office. So I downloaded and I'm trying to add to my project. Have issue running on real device. And how to test connection using eclipse paho

**Comment by HJianBo** [comment]
Hi, @sharihv  Could you paste the error log on the real deivce?

**Comment by sharihv** [comment]
I'm using pods now. It's running on real device.My issue is testing it. I give host and port number and its not connecting. It ends up in mqttDidDisconnect with error Code =7 " Socket closed by remote peer".
Tried with Eclipse Paho, EMQ

**Comment by sharihv** [comment]
var mqttClient : CocoaMQTT!

//The below method is called in viewDidLoad().

func configureMQTT() {
    let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
    let host = "iot.eclipse.org"
    let port = UInt16(443)
    mqttClient = CocoaMQTT(clientID: clientID, host: host, port: port)
    mqttClient.username = ""
    mqttClient.password = ""
    mqttClient.willMessage = CocoaMQTTWill(topic: "world", message: "hello)
    mqttClient.keepAlive = 60
    mqttClient.connect()
}


// The delegate methods:

extension ViewController: CocoaMQTTDelegate {

    func mqtt(_ mqtt: CocoaMQTT, didConnect host: String, port: Int) {
    }
    
    func mqtt(_ mqtt: CocoaMQTT, didReceiveMessage message: CocoaMQTTMessage, id: UInt16 ) {
    }
    
   
    func mqtt(_ mqtt: CocoaMQTT, didReceive trust: SecTrust, completionHandler: @escaping (Bool) -> Void) {
        completionHandler(true)
    }
    
    func mqtt(_ mqtt: CocoaMQTT, didConnectAck ack: CocoaMQTTConnAck) {
    }
    
    func mqtt(_ mqtt: CocoaMQTT, didPublishMessage message: CocoaMQTTMessage, id: UInt16) {
    }
    
    func mqtt(_ mqtt: CocoaMQTT, didPublishAck id: UInt16) {
    }
    
    func mqtt(_ mqtt: CocoaMQTT, didSubscribeTopic topic: String) {
    }
    
    func mqtt(_ mqtt: CocoaMQTT, didUnsubscribeTopic topic: String) {
    }
    
    func mqttDidPing(_ mqtt: CocoaMQTT) {
    }
    
    func mqttDidReceivePong(_ mqtt: CocoaMQTT) {
    }
    
    func mqttDidDisconnect(_ mqtt: CocoaMQTT, withError err: Error?) {
       Print ("Disconnected \(String(describing:err))")
    }
   }

When tried with Eclipse paho I get the same error.Is there anything I'm missing??

**Comment by HJianBo** [comment]
**The 443 port is used by SSL connection**. But your CocoaMQTTClient don't configure for this.

If you want to create a secure connection by CocoaMQTT, you should set CocoaMQTTClient like this:
https://github.com/emqtt/CocoaMQTT/blob/d386034adaf46842626f64781a6a622517f8c4c6/Example/Example/ViewController.swift#L67-L83

In another solution. Modify the port to 1883 for connecting a common  TCP port:
```swift
let port = UInt16(1883)
```

**Comment by sharihv** [comment]
I tried with port 1883.It connected and I received the message too.But after some 6s it is getting disconnected.How do I keep the connection alive?

**Comment by HJianBo** [comment]
Hi, @sharihv Sorry too late reply.

Is the problem has resolved?
