### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by KevinCoderX** [emqtt/CocoaMQTT#255]
Swift5 is coming!

**Comment by HJianBo** [comment]
Awesome! We'll support it as soon as possible.

Thanks for your feedback!

**Comment by telecoder** [comment]
Hooray!!! My code no longer compiles!

**Comment by KevinCoderX** [comment]
@telecoder You can import sourceFile to your project manually

**Comment by HJianBo** [comment]
Hi, guys I have released the v1.2.0 that supported swift 5.
