### ISSUE TITLE
Carthage: Task failed with exit code 65:

### ISSUE THREAD

**Issue by KevinCoderX** [emqtt/CocoaMQTT#258]
In CocoaMQTT 1.2.0

![image](https://user-images.githubusercontent.com/15177149/57175848-26121080-6e83-11e9-9381-a37cd65d38af.png)

**Comment by HJianBo** [comment]
Hi, @KevinCoderX can you send me the xcodebuild log file to me emai: heeejianbo@gmail.com

**Comment by HJianBo** [comment]
Can you paste the carthfile? and What's the Carthage command used?

**Comment by KevinCoderX** [comment]
#Swift
github "Alamofire/Alamofire"
github "SwiftyJSON/SwiftyJSON"
github "SnapKit/SnapKit"
github "danielgindi/Charts"
github "jonkykong/SideMenu"
github "jkpang/PPBadgeView"
github "hackiftekhar/IQKeyboardManager"
github "onevcat/Kingfisher"
github "krzysztofzablocki/LifetimeTracker"
github "radex/SwiftyTimer"
github "daltoniam/Starscream"
github "emqtt/CocoaMQTT"

#Objective-C
github "SVProgressHUD/SVProgressHUD"
github "robbiehanson/CocoaAsyncSocket"

carthage update --platform iOS

Last update, Xcode builded CocoaMQTT successfully

**Comment by HJianBo** [comment]
> Last update, Xcode builded CocoaMQTT successfully

So the problem has been resolved?

**Comment by KevinCoderX** [comment]
It's ok for me.
