### ISSUE TITLE
Crash removeFrameFromInflight

### ISSUE THREAD

**Issue by ariefnurputranto** [emqtt/CocoaMQTT#272]
Hi . . .
im using cocoaMQTT v1.2.1, sometime i getting crash in removeFrameFromInflight

![Screen Shot 2019-06-12 at 11 33 47](https://user-images.githubusercontent.com/12388348/59323748-2f09c380-8d06-11e9-9b7a-9cd5cce58ec1.png)

**Comment by HJianBo** [comment]
Duplicated #271
