### ISSUE TITLE
does this framework support VOIP protocol?

### ISSUE THREAD

**Issue by qifx** [emqtt/CocoaMQTT#37]
When i push the home button of iPhone, app goes to background and the socket connection is closed. IOS support VIOP background module. APP use this module, IOS system can take over the socket connection when APP goes to background. When socket reveive something, IOS system wake app up for a moment to do with it.

**Comment by CrazyWisdom** [comment]
I did a test, when i push the home button of iPhone, the callback `mqttDidReceivePong(mqtt: CocoaMQTT) {}`  can still be executed, and the soectet has not been closed.

You could download my latest test code from https://github.com/CrazyWisdom/CocoaMQTT, then run the  Example project in it, and click the "Connect" button in the navigation bar.

**Comment by qifx** [comment]
I tested your example, the ping pong log print only when the app is on foreground. It likes a reconnect, it prints many logs after i wait a long time at the background state.

**Comment by qifx** [comment]
I found a file:https://github.com/Guou/Demo-mqtt-push/blob/master/MQTTKit/MQTTKit/MQTTKit.m
A line like "CFReadStreamSetProperty(readStream, kCFStreamNetworkServiceType, kCFStreamNetworkServiceTypeVoIP);" is about set socket property to VOIP

**Comment by CrazyWisdom** [comment]
Okay,I will have a look.

**Comment by CrazyWisdom** [comment]
@qifx , you could enable VOIP mode use: mqtt.backgroundOnSocket = true
https://github.com/emqtt/CocoaMQTT/pull/40
