### ISSUE TITLE
How to use this library in OC project？

### ISSUE THREAD

**Issue by shanyulaile** [emqtt/CocoaMQTT#38]
I want to use this library in OC project, could you tell me how to use？

**Comment by CrazyWisdom** [comment]
0. Install CocoaMQTT using CocoaPods
1. Choose the OC project
2. Choose the project name in the TARGETS list
3. Click the Build Settings tab
4. In the Build Options section, make sure the option Embedded Content Contains Swift Code is YES, and Defines Module is YES
5. Now, you can import CocoaMQTT framework into any Objective-C .m
    like: @import CocoaMQTT;

**Comment by shanyulaile** [comment]
This process is how to generate the project name - swift. h file
