### ISSUE TITLE
Support XCode 13 in cocoapods

### ISSUE THREAD

**Issue by ariefnurputranto** [emqtt/CocoaMQTT#403]
hi @HJianBo , or other dev cocoaMqtt.

We need help to support XCode 13 in CocoaPods. 

Thanks

**Comment by leeway1208** [comment]
[CocoaMQTTTypes.zip](https://github.com/emqx/CocoaMQTT/files/7303415/CocoaMQTTTypes.zip)
hi guys, please replace original two files with this attachments to fix issue or try to use dev/2.0 branch
