### ISSUE TITLE
Using the framework of the mistakes in the oc

### ISSUE THREAD

**Issue by shanyulaile** [emqtt/CocoaMQTT#44]
1.Install CocoaMQTT using CocoaPods
2.Choose the OC project
3.Choose the project name in the TARGETS list
4.Click the Build Settings tab
5.In the Build Options section, make sure the option Embedded Content Contains Swift Code is YES, and Defines Module is YES
6.Now, you can import CocoaMQTT framework into any Objective-C .m like: @import CocoaMQTT;

According to the above method in the oc use this frame the following mistakes，How to solve？
![2016-03-07 10 14 09](https://cloud.githubusercontent.com/assets/11886729/13559280/66690332-e44d-11e5-902e-df088e4bd688.png)

**Comment by anagram** [comment]
take a look at MQTTKit.h
There is no property 'willMessage' just as the error states.
look at the Connection methods such as:
- (void)setWillData:(NSData *)payload
            toTopic:(NSString *)willTopic
            withQos:(MQTTQualityOfService)willQos
             retain:(BOOL)retain;

**Comment by shanyulaile** [comment]
Before I use is Mqttkit, when using point-to-point push news appeared a repeat link problem.
So want to find a solution here, but I'm using the object - C, the use is swift, mix in the problem，how to solve this problem

**Comment by CrazyWisdom** [comment]
@shanyulaile , fix commit: https://github.com/emqtt/CocoaMQTT/pull/45 .
pods version will be updated tomorrow.

**Comment by CrazyWisdom** [comment]
@shanyulaile, fix in pod version: 1.0.1, you can pod update.
