### ISSUE TITLE
Resending messages which never received a PubAck

### ISSUE THREAD

**Issue by pzuraq** [emqtt/CocoaMQTT#46]
Currently it looks like when messages are given qos > 0, they are persisted in a Dictionary field named `messages`

https://github.com/emqtt/CocoaMQTT/blob/master/Source/CocoaMQTT.swift#L228-L242

This field is private and appears to be used for this and some QOS2 related concerns. However, as far as I can tell there isn't a mechanism to attempt to retry sending these messages, and since the field is private there isn't a way for users to do this in their apps.

Would it make sense to make the messages field public so that users could A. resend messages and B. show the status of messages to users?

**Comment by CrazyWisdom** [comment]
https://github.com/emqtt/CocoaMQTT/pull/57
