### ISSUE TITLE
Manual disconnection did not work as expected

### ISSUE THREAD

**Issue by ckfear** [emqtt/CocoaMQTT#465]
I call `mqtt.disconnect`,but it still reconnect.I found the variable `is_internal_disconnected` is always true.
```swift
public func disconnect() {
    is_internal_disconnected = false
    internal_disconnect()
}
    
/// Disconnect unexpectedly
func internal_disconnect() {
    is_internal_disconnected = true
    send(FrameDisconnect(), tag: -0xE0)
    socket.disconnect()
}
```

And the automatic reconnection logic doesn't look right.

```swift
if !autoReconnect{
    guard !is_internal_disconnected else {
        return
    }
}

guard autoReconnect else {
    return
}
```
The above code makes the `is_internal_disconnected` variable meaningless.As I understand it, if I disconnect from the outside, it should not automatically reconnect.

**Comment by ckfear** [comment]
I submitted the pr #466  to fix the problem.

**Comment by leeway1208** [comment]
Thank you for your support.😄

**Comment by ckfear** [comment]
It's ok.But I think external disconnection and internal disconnection should be different behaviours. And the parameter is_internal_disconnected should work.

**Comment by leeway1208** [comment]
@ckfear Yes. you are right. I misunderstood. Thank you for your contribution!
