### ISSUE TITLE
Cannot build watchOS and OSX schemes

### ISSUE THREAD

**Issue by stansidel** [emqtt/CocoaMQTT#47]
I tried to build all the schemes of the project to get it ready for Carthage. But I couldn't do that for two of the schemes: watchOS and OSX.

There's an error for the watchOS target:

    /Users/user/Projects/CocoaMQTT/Source/CocoaMQTT.swift:291:32: Use of unresolved identifier 'kCFStreamSSLPeerName'

And another one for OSX:

    /Users/user/Projects/CocoaMQTT/Source/CocoaMQTT.swift:284:33: Value of type 'GCDAsyncSocket' has no member 'enableBackgroundingOnSocket'

As I don't need those schemes for my project now I didn't go deep into those errors. But I think it's important to state them here. I used Xcode Version 7.2.1 (7C1002) for building. There'd been no changes made to the project prior to building.

**Comment by CrazyWisdom** [comment]
1.Because CocoaAsyncSocket framework not  support  watchOS
2.I submit a issue to  CocoaAsyncSocket https://github.com/robbiehanson/CocoaAsyncSocket/issues/412

**Comment by stansidel** [comment]
For the first point, may I suggest to remove the scheme for tvOS from the project then? Or at least to add a note about it in the README?

**Comment by CrazyWisdom** [comment]
ok
