### ISSUE TITLE
Support MQTT 3.1.1

### ISSUE THREAD

**Issue by andypiper** [emqtt/CocoaMQTT#5]
Per http://www.hivemq.com/6-facts-why-its-worth-upgrading-to-mqtt-3-1-1/

Currently only supports protocol level 3 / MQIsdp identifier.

**Comment by hankbao** [comment]
Hi @erylee, do you get ETA for this? BTW, thanks for providing CocoaMQTT.

**Comment by erylee** [comment]
@hankbao, I will upgrade this library to MQTT v3.1.1 later...

**Comment by hankbao** [comment]
Great. :+1:

**Comment by erylee** [comment]
@hankbao, upgrade to MQTT v3.1.1, please check PR: https://github.com/emqtt/CocoaMQTT/pull/16

**Comment by hankbao** [comment]
@erylee Thanks
