### ISSUE TITLE
Error of build if add 1.0.1 version via CocoaPods. 

### ISSUE THREAD

**Issue by AlexIzh** [emqtt/CocoaMQTT#53]
![screen shot 2016-03-11 at 13 57 46](https://cloud.githubusercontent.com/assets/2103547/13699024/4432d1b6-e791-11e5-83ab-36c4e2cee8e2.png)

For 1.0.0 version all was good, after updating to 1.0.1 I get error (se screenshot)

**Comment by CrazyWisdom** [comment]
swift or objective-c project:  xcode 7.2.1 , pod 1.0.0.beta.4, works fine. 
what yours?
my Podfile is:
`platform :ios, 9.0
use_frameworks!
target 'SwiftDemo' do
    pod 'CocoaMQTT'
end`

Sometimes there are many errors, but you can still try to compile, then errors may disappear.

**Comment by AlexIzh** [comment]
Hm, I have swift project, xcode 7.2.1, pod 0.39.0
My Podflie:

    platform :ios, ‘8.0’
    use_frameworks!
    target ‘App’ do
        pod ‘CocoaMQTT’
    end

Yes, I know regarding error which may disappear, but I cannot compile with this error :(

**Comment by CrazyWisdom** [comment]
oh, I have the same error with pod 0.39
Give me some time.

**Comment by AlexIzh** [comment]
Thank you for the very quick response

**Comment by CrazyWisdom** [comment]
fixed in pod version 1.0.3
you can reinstall now.
