### ISSUE TITLE
Error when subscribing to multiple topics  

### ISSUE THREAD

**Issue by reese07** [emqtt/CocoaMQTT#59]
You should either make connState property public so a dev could check if already connected. If not here are the steps I took to get to the error below

0. We have a few topics
1. When I subscribe to first topic everything works
2. When I want to subscribe to another topic. I am assuming that it automatically disconnects from the first topic internally because I stop receiving messages and start receiving messages from new inserted topic
3. Now if I try to connect to that first topic I get the error message below crash. 

I would disconnect to the first topic if connState was available.

assertion failed: : file /Pods/CocoaMQTT/Source/CocoaMQTT.swift, line 581

**Comment by CrazyWisdom** [comment]
@reese07 https://github.com/emqtt/CocoaMQTT/pull/62
