### ISSUE TITLE
no such moudle ’CocoaAsyncSocket

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/CocoaMQTT#64]
follow this step
$ git init
Add CocoaMQTT as a git submodule by running the following command:
$ git submodule add https://github.com/emqtt/CocoaMQTT.git

CocoaPods

Install using CocoaPods by adding this line to your Podfile:

use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
pod 'CocoaMQTT'  
Then, run the following command:

$ pod install
Last, creat a CocoaMQTT-Bridging-Header.h file in your project, in which add the following line:

#import "CocoaMQTT/CocoaMQTT.h"

xcode 7.2 
//
//  CocoaMQTT.swift
//  CocoaMQTT
//
//  Created by Feng Lee<feng@eqmtt.io> on 14/8/3.
//  Copyright (c) 2015 emqtt.io. All rights reserved.
//

import Foundation
import CocoaAsyncSocket   **--- no such moudle ’CocoaAsyncSocket ‘**

import MSWeakTimer

**Comment by CrazyWisdom** [comment]
Sorry，the document has not been updated, now you do not need to create  CocoaMQTT-Bridging-Header.h

**Comment by lsxredrain** [comment]
CocoaPods , Carthage and Manual should done step by step?
I follow CocaPods and Manual, the project will compile failed for "import CocoaAsyncSocket --- no such moudle ’CocoaAsyncSocket ‘

**Comment by CrazyWisdom** [comment]
Does not need select all, just select one:  CocoaPods  Carthage or Manual

**Comment by CrazyWisdom** [comment]
@lsxredrain ,you can recreate a project, just use CocoaPods.

**Comment by lsxredrain** [comment]
follow those step:
$ git init
$git init$ git submodule add https://github.com/emqtt/CocoaMQTT.git
$cd CocacaMQTT
$vi  Podfile
$cat Podfileplatform :ios, 9.0
use_frameworks!

pod 'CocoaAsyncSocket'
pod 'MSWeakTimer'
pod 'CocoaMQTT'
$pod install
open CocoaMQTT.xcodeproj 
then compile this project in Xcode, it will find three compile error/Users/lsx/workbase/CocoaMQTT/Source/CocoaMQTT.swift:364:27: Expected expression in list 
of expressions
/Users/lsx/workbase/CocoaMQTT/Source/CocoaMQTT.swift:364:27: Expected ',' separator/Users/lsx/workbase/CocoaMQTT/Source/CocoaMQTT.swift:10:8: No such module 'CocoaAsyncSocket'

**Comment by CrazyWisdom** [comment]
just two step:

1.create the Podfile with follow content:
`use_frameworks!
pod 'CocoaMQTT' `

2.excude the command:
`pod install`

**Comment by lsxredrain** [comment]
CocoaPods 1.0.0.beta.8 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

    xcodeproj 'path/to/Project.xcodeproj'

**Comment by CrazyWisdom** [comment]
What is your pod version ?

My pod version is 0.39.0.

You can change the Podfile to follow:
--remember to replace Project name 
```
use_frameworks!
target "Project name" do
    pod ''CocoaMQTT"
end
```

**Comment by lsxredrain** [comment]
lsxdeMacBook-Pro:CocaMQTT lsx$ pwd
/Users/lsx/workbase/CocaMQTT
lsxdeMacBook-Pro:CocaMQTT lsx$ ls
lsxdeMacBook-Pro:CocaMQTT lsx$ cat Podfile 
platform :ios, 9.0
use_frameworks!
pod 'CocoaMQTT'lsxdeMacBook-Pro:CocaMQTT lsx$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.8 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

    xcodeproj 'path/to/Project.xcodeproj'

**Comment by CrazyWisdom** [comment]
1. first,  you should create an xcode project
2. create a Podfile in the project folder
3. excute command `pod install`

like my test project:
```
➜  swifttest ls
Podfile               Pods                  swifttest.xcodeproj
Podfile.lock          swifttest             swifttest.xcworkspace
➜  swifttest 
```

**Comment by lsxredrain** [comment]
1 create null project as named CocoaHell in Xcode 7.2
2 create Podfile
3 pod install

localhost:CocoaHello lsx$ ls
CocoaHello		Podfile			uncrustify.cfg
CocoaHello.xcodeproj	Podfile.lock
CocoaHello.xcworkspace	Pods
localhost:CocoaHello lsx$ cat Podfile
platform :ios, '9.0'
use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
pod 'CocoaMQTT'localhost:CocoaHello lsx$ ls Pods/
CocoaAsyncSocket	Local Podspecs		Pods.xcodeproj
CocoaMQTT		MSWeakTimer		Target Support Files
Headers			Manifest.lock

still have error 
ld: framework not found CocoaAsyncSocketclang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lsxredrain** [comment]
//CocoaMQTTReader Delegate

    public func didReceiveConnAck(reader: CocoaMQTTReader, connack: UInt8) {
        connState = CocoaMQTTConnState.CONNECTED
        #if DEBUG
        NSLog("CocoaMQTT: CONNACK Received: \(connack)")
        #endif
 
        let ack = CocoaMQTTConnAck(rawValue: connack)!
        delegate?.mqtt(self, didConnectAck: ack)
        
        //keep alive
       //begin commit by lsxredrain 2016-4-21,then will compile sucessed
        if ack == CocoaMQTTConnAck.ACCEPT && keepAlive > 0 {
        //    aliveTimer = MSWeakTimer.scheduledTimerWithTimeInterval(ß
         //       NSTimeInterval(keepAlive),
          //      target: self,
           //     selector: #selector(CocoaMQTT._aliveTimerFired),
            //    userInfo: nil,
             //   repeats: true,
               // dispatchQueue: dispatch_get_main_queue())
        }
        //end 
    }

**Comment by CrazyWisdom** [comment]
use the xcode7.3

**Comment by lsxredrain** [comment]
i can't use Xcode 7.3 for my os is 10.10， can u add selector: #selector(CocoaMQTT._aliveTimerFired) for Xcode 7.2？

**Comment by CrazyWisdom** [comment]
you can change `selector: #selector(CocoaMQTT._aliveTimerFired)`
to ` selector: "_aliveTimerFired",`

**Comment by lsxredrain** [comment]
ok thanks a lot！
as a newcomer of swift, I should study this article first
http://blog.csdn.net/eqera/article/details/39312125
