### ISSUE TITLE
No IOS 7 support

### ISSUE THREAD

**Issue by brstgt** [emqtt/CocoaMQTT#67]
Hi Guys,

First, thanks for building a neat Swift MQTT lib!
But is it really necessary to set the minimum IOS version to 8.0? There are still a lot of projects out there that support IOS 7. Of course, nobody wants to but there really are still some users out there. In our case, still 6% of all IOS users have IOS 7.x

I would be very grafeful if you could take a look and maybe decide to support 7.0
Otherwise I have to use a different (ObjC) lib.

Have a nice day!

**Comment by lacklock** [comment]
you can copy source files to your project to support iOS7.
because dynamic framework only support iOS8, so if using package manage ,it's can't support iOS7

**Comment by shenyuanluo** [comment]
Hi,
    When I download 'zip' code and build it today. But there was wrong with ' try -- catch'. I don't have change any , What should I do? Who can  tell me how to fix it ?

**Comment by CrazyWisdom** [comment]
@shenyuanluo, you can use `pod install CocoaMQTT` to install
