### ISSUE TITLE
SSL connection with RabbitMQ

### ISSUE THREAD

**Issue by andreamazz** [emqtt/CocoaMQTT#71]
Hi all
Did you ever try to connect this MQTT client to a rabbitMQ instance using SSL?
I'm having a hard time doing so, maybe you have some suggestions
Here's the code I'm using:
```swift
    mqttClient = CocoaMQTT(clientId: "client", host: host, port: 8883)
    mqttClient?.secureMQTT = true
    mqttClient?.username = username
    mqttClient?.password = password
    mqttClient?.keepAlive = 90
    mqttClient?.delegate = self
    mqttClient?.connect()
```
This results in this error:
```
Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}
```

The endpoint is working correctly, other clients (written in other languages) are working fine.  
I was able to connect using [ckrey/MQTT-Client-Framework](https://github.com/ckrey/MQTT-Client-Framework), but I rather use this library instead :)

**Comment by andreamazz** [comment]
If this can help, you can test the ssl connection using the test endpoint provided by Mosquitto:
```swift
    mqttClient = CocoaMQTT(clientId: "clientid", host: "test.mosquitto.org", port: 8883)
    mqttClient?.secureMQTT = true
    mqttClient?.username = "user"
    mqttClient?.password = "password"
    mqttClient?.keepAlive = 90
    mqttClient?.delegate = self
    mqttClient?.connect()
```

You'll need to add [this cert](http://test.mosquitto.org/ssl/mosquitto.org.crt) to your keychain.

It's also worth noting that RabbitMQ enforces the use of TLSv1.2. I had to change the dictionary provided to the `startTLS` function to include these two options, sadly to no avail:
```
GCDAsyncSocketSSLProtocolVersionMin: 8, 
GCDAsyncSocketSSLProtocolVersionMax: 8
```

**Comment by andreamazz** [comment]
After some further digging, looks like that the SSL connection is correctly established, our backend closes the connection with this error:
```
MQTT protocol error connect_expected for connection 
```

Without SSL the connection works flawlessly.

**Comment by andreamazz** [comment]
Ok, figured it out. It's a timing issue.
I was subscribing in a completion block triggered by the `didConnect` delegate. This is fine when done in plain MQTT, but not when using SSL, as you can see here:
https://github.com/emqtt/CocoaMQTT/blob/master/Source/CocoaMQTT.swift#L303
the delegate is called right away, but it should be called once the secure channel is created, in the `socketDidSecure` delegate method.

**Comment by CrazyWisdom** [comment]
thanks

**Comment by andreamazz** [comment]
Thanks for merging. 
Are you planning a new release any time soon? I would greatly appreciate that (I'm using this as a dependency for another podspec, so I need to reference a version).

**Comment by CrazyWisdom** [comment]
Yes, tomorrow or the day after tomorrow

**Comment by andreamazz** [comment]
Thanks.

**Comment by CrazyWisdom** [comment]
@andreamazz , v1.0.7 released.

**Comment by andreamazz** [comment]
Great, thank you 👍
