### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by Techchunky** [emqtt/CocoaMQTT#73]
Hi,

Can I check if there are multile mqtt.connect() ?

**Comment by Sufi-Al-Hussaini** [comment]
It's not clear what you're asking.

If you need to check whether or not you are connected, use `CocoaMQTT.connState` (see pull request #62 ).

If you need to make sure you only have one `CocoaMQTT` instance in your app you should make use of singletons. See [this implementation](https://github.com/MichMich/HomeSensor/blob/master/HomeSensor/MQTTManager.swift).
