### ISSUE TITLE
Assertion Causes Crash?

### ISSUE THREAD

**Issue by WilliamHua** [emqtt/CocoaMQTT#74]
Inside CocoaMQTT.swift, in the frameReady() function, on the switch function if the frameType is undetermined there is a force crash with assert(false).

My app is sometimes crashing on this (I can't figure out what's causing this as it does not happen all the time). 

I'm not sure if this is an issue with the library or my implementation, do you have any thoughts on this?

Other than this issue, the MQTT library seems to be working perfectly.

**Comment by CrazyWisdom** [comment]
@WilliamHua, What mqtt broker are you using? emqtt?
Could you please print the frameType value in the frameReady() to me if  the crash happens?

**Comment by karpy47** [comment]
I have experienced exactly the same crash as @WilliamHua. It happens irregularly, so it's hard to reproduce. However, frameType value was 0 (reserved) and we're using Apache ActiveMQ as message server.
Could it by that the socket reading goes out of sync (loosing bytes)?

**Comment by CrazyWisdom** [comment]
@WilliamHua @karpy47 , https://github.com/emqtt/CocoaMQTT/pull/77
