### ISSUE TITLE
two or more connections management 

### ISSUE THREAD

**Issue by Drenadan** [emqtt/CocoaMQTT#76]
HI, could you please help with issue:

If I created 2 or more connections, how I can stop specific session ? 
Maybe I can specify for example - mqtt!."Some unique identifier like a clientId or port".disconnect() ?

**Comment by CrazyWisdom** [comment]
@Drenadan 
```
mqtt1 = CocoaMQTT(clientId: "id1", host: "localhost", port: 1883)
mqtt2 = CocoaMQTT(clientId: "id2", host: "localhost", port: 1883)

mqtt1.disconnect()
mqtt2.disconnect()
```
