### ISSUE TITLE
Message ID

### ISSUE THREAD

**Issue by knichwitz** [emqtt/CocoaMQTT#79]
We encountered a bug with your _nextMessageId() function.
When it reaches the max value the whole app crashes.
We fixed this bug with rewriting your code:

CocoaMQTT.swift
```
func _nextMessageId() -> UInt16 {
        if amid == UInt16.max {
            amid = 0
        }
        amid += 1
        return amid
    }
```

**Comment by CrazyWisdom** [comment]
@knichwitz , thanks. https://github.com/emqtt/CocoaMQTT/pull/80
