### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by piotr-tobolski** [emqtt/CocoaMQTT#81]
Please add Swift 3.0 support!

**Comment by Patrick2990** [comment]
Could be really nice with swift 3 support! Thank you

**Comment by Jeraimee** [comment]
I'll start looking at this tonight.

**Comment by troyibm** [comment]
How about making it compile with Swift 2.3 first?
When using Xcode 8 and carthage, I get this error when it starts to build CocoaMQTT.
```
=== BUILD TARGET CocoaMQTT iOS OF PROJECT CocoaMQTT WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

**Comment by Jeraimee** [comment]
Compiles fine in Swift 2.3 @troyibm You have to set Use Legacy Swift Language Version in your build settings. I'm using it in a Swift 2.3 project right now.

**Comment by Jeraimee** [comment]
Won't get to look at this until tomorrow. I forgot that AHS starts back up tonight ... you know, priorities and all ;)

**Comment by troyibm** [comment]
thanks @Jeraimee is there a way to put that setting on carthage command? do you know?

**Comment by Jeraimee** [comment]
No, it's specific to your Xcode project.

**Comment by troyibm** [comment]
I think it would help if the project.pbxproj file had the line 
`
                                SWIFT_VERSION = 2.3;
`
in it, then carthage build would work with Xcode 8.

**Comment by adad184** [comment]
looking for 3.0 support too.

**Comment by netgfx** [comment]
yes carthage still fails on master

**Comment by CrazyWisdom** [comment]
https://github.com/emqtt/CocoaMQTT/releases/tag/1.0.10
Cocoapods pushed.
