### ISSUE TITLE
Running the example project fails

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [emqtt/CocoaMQTT#84]
I downloaded and ran the example project on an iPhone 5. But it fails with the following error.

> dyld: Library not loaded: @rpath/CocoaAsyncSocket.framework/CocoaAsyncSocket
  Referenced from: /private/var/containers/Bundle/Application/F1106E5F-A377-49BC-B09D-5BB5BDB4FD0D/Example.app/Frameworks/CocoaMQTT.framework/CocoaMQTT
  Reason: image not found

**Comment by Sufi-Al-Hussaini** [comment]
Related to this [stackoverflow question](http://stackoverflow.com/questions/24993752/os-x-framework-library-not-loaded-image-not-found). Essentially what you need to do is `add the framework to the "Embedded binaries" section in the "General" tab of your app target`, and amke sure you open the `CocoaMQTT.xcworkspace` file.

**Comment by CrazyWisdom** [comment]
@Isuru-Nanayakkara 
execute ` pod install` in the CocoaMQTT folder

**Comment by Isuru-Nanayakkara** [comment]
@CrazyWisdom I did. But still got the error. I had to change the `Podfile` a little though because CocoaPods v1.0 upwards require specific mentions of targets in the Podfile.

This is what I did.

```
platform :ios, '8.0'

target 'CocoaMQTT iOS' do
  use_frameworks!

  pod 'CocoaAsyncSocket'
  pod 'MSWeakTimer'

  target 'CocoaMQTT iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CocoaMQTT OSX' do
  use_frameworks!

  pod 'CocoaAsyncSocket'
  pod 'MSWeakTimer'

  target 'CocoaMQTT OSXTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CocoaMQTT tvOS' do
  use_frameworks!

  pod 'CocoaAsyncSocket'
  pod 'MSWeakTimer'

  target 'CocoaMQTT tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

Don't know maybe that's the issue.

**Comment by CrazyWisdom** [comment]
@Isuru-Nanayakkara 
1.`git clone https://github.com/emqtt/CocoaMQTT.git`
2. Open CocoaMQTT.xcworkspace, then run the example project, don't need to execute `pod install`

**Comment by Isuru-Nanayakkara** [comment]
Tried this again. But no luck. Weird. Same issue.
> dyld: Library not loaded: @rpath/CocoaAsyncSocket.framework/CocoaAsyncSocket
  Referenced from: /private/var/containers/Bundle/Application/0A049A93-4FC8-4B7F-938C-08C900250C9C/Example.app/Frameworks/CocoaMQTT.framework/CocoaMQTT
  Reason: image not found

**Comment by CrazyWisdom** [comment]
Clone into another folder?  I tested success

**Comment by dimohamdy** [comment]
@CrazyWisdom  not work

**Comment by dimohamdy** [comment]
@Isuru-Nanayakkara  did you solve it?

**Comment by Isuru-Nanayakkara** [comment]
@dimohamdy No, I couldn't get it working either.

**Comment by CrazyWisdom** [comment]
@dimohamdy, git clone the latest CocoaMQTT(I just updated the code), cd the Example folder execute `pod install`, then `open Example.xcworkspace`
