### ISSUE TITLE
Support IPv6 with non-standart port Issue

### ISSUE THREAD

**Issue by Rolvar** [emqtt/CocoaMQTT#86]
Hi, I have some issues trying to connect to my mqtt server with a domain name that returns an IPv4, and GCDAsyncSocket cant digest over an IPv6 network. I ran step by step to tried to figured out what's happened, and I think that maybe it is because I use an numeric port and the "getaddrinfo" cant resolve it.

Can you help me with this issue please, my app was rejected by Apple because of this.

Thanks in advance.

**Comment by Rolvar** [comment]
I use [MQTTClient](https://github.com/ckrey/MQTT-Client-Framework) library instead CocoaMQTT and now everything is working perfect, I hope that you can find what it is happening with CocoaMQTT on IPv6 networks.

**Comment by jpmcglone** [comment]
hey @Rolvar did you figure out if it was in fact CocoaMQTT causing the issue? We are also getting rejected.

**Comment by Rolvar** [comment]
hi @jpmcglone 

Not at all, I think that the problem was on CocoaAsyncSocket but I'm not sure at all, something it is wrong with the lookupHost function on [GDAAsyncSocket (line 7992)](https://github.com/emqtt/CocoaMQTT/blob/master/Pods/CocoaAsyncSocket/Source/GCD/GCDAsyncSocket.m#L7992) for some strange reason the port can't be mapped to an IPv6 address if you pass an numeric (or string) port like '8888'. you have to use an standard and known port instead like 'http' or 'ftp' and so on.

If you pass an numeric and unknown port, the getaddrinfo() function will be map as '0' and you never will get an valid IPv6 address.

So, I had to search another MQTT library, and I found [MQTTClient from Christoph Krey](https://github.com/ckrey/MQTT-Client-Framework) and now everything is working fine and my app successfully passed Apple's review.

**Comment by emqplus** [comment]
Hi @CrazyWisdom, please fix the issue.

**Comment by CrazyWisdom** [comment]
Hi all, you can ues the latest version 1.0.8(https://github.com/emqtt/CocoaMQTT/releases/tag/1.0.8)
