### ISSUE TITLE
CocoaMQTT Memory Leak?

### ISSUE THREAD

**Issue by emqplus** [emqtt/CocoaMQTT#89]
Mail from Stolarski:

I’m using your library for the last few months, and In the last few days I’m trying to trace a memory leak in my app, which I believe is coming from the mqtt publisher.

When I’m looking at the memory allocations using apple’s leaks instrumentation tool, I can see a ContiguousArrayStorage<Uint8> is being allocated each time a message is being sent. This array doesn’t seem to be released during the app life, and because my app send messages every few minutes, it ends with ~600Kb being allocated every 2-3 minutes, which causes the app to crash eventually after few hours/days.

**Comment by CrazyWisdom** [comment]
https://github.com/emqtt/CocoaMQTT/pull/91

**Comment by nivsto** [comment]
Thanks!
