### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by yasirtahir** [emqtt/CocoaMQTT#98]
I have a MQTT over WebSocket host with NodeRed. I am using this library in order to connect but I am getting the following error:

Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer} 

Code:
let clientIdPid = "CocoaMQTT-" + String(NSProcessInfo().processIdentifier)
let mqtt = CocoaMQTT(clientId: clientIdPid, host: "95.177.135.232", port: 9001)  
mqtt.cleanSess = true
mqtt.keepAlive = 60
mqtt.delegate = self
mqtt.connect()

**Comment by CrazyWisdom** [comment]
Is 9001 the WebSocket port? CocoaMQTT now only supports tcp connections.

**Comment by Decrypto** [comment]
FWIW, since updating to Swift 3 I've been getting the same:

`Did disconnect with error: Optional(Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer})`

This is against AdafruitIO, io.adafruit.com:1883
Sometimes it will stay connected for a few pings. Sometimes it resets almost immediately. KeepAlive = 90.

**Comment by axpence** [comment]
I'm having this issue as well. Any ideas?
```
    func mqttSetting() {
//        let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
        let clientID = "myclientid_101"
        mqtt = CocoaMQTT(clientID: clientID, host: "159.203.240.39", port: 8000)
//        mqtt!.username = ""
//        mqtt!.password = ""
//        mqtt!.willMessage = CocoaMQTTWill(topic: "/will", message: "dieout")
        mqtt!.keepAlive = 90
        mqtt!.cleanSession = true
//        mqtt?.secureMQTT = true
        mqtt!.delegate = self
    }
```

I have tried about every permutation of the commented out settings... still no luck

**Comment by alexyu1989** [comment]
@axpence I have tried your host. The host's port 8000 fail, but port 1883 succeed. Please check your host port 8000. Thanks.

**Comment by axpence** [comment]
@alexyu1989 nice name :). You are correct, I had the incorrect port. Thanks for your help! Sorry for the n00b question.

**Comment by alexyu1989** [comment]
@axpence You are welcome. Have fun with the framework :)
